package main

const EGTS_SR_RECORD_RESPONSE = 0
const EGTS_SR_POS_DATA = 16
const EGTS_SR_EXT_POS_DATA = 17
const EGTS_SR_AD_SENSORS_DATA = 18
const EGTS_SR_COUNTERS_DATA = 19
const EGTS_SR_STATE_DATA = 20
const EGTS_SR_LOOPIN_DATA = 22
const EGTS_SR_ABS_DIG_SENS_DATA = 23
const EGTS_SR_ABS_AN_SENS_DATA = 24
const EGTS_SR_ABS_CNTR_DATA = 25
const EGTS_SR_ABS_LOOPIN_DATA = 26
const EGTS_SR_LIQUID_LEVEL_SENSOR = 27
const EGTS_SR_PASSENGERS_COUNTERS = 28

